"""Dispatch table for lease-free addon integrations."""
from __future__ import annotations

from typing import Any, Callable, Dict, Optional

from exo_control import (
    agentql_ops,
    composio_ops,
    docling_ops,
    everything_ops,
    files_plus_ops,
    firecrawl_ops,
    git_ops,
    github_ops,
    graph_ops,
    jina_ops,
    markitdown_ops,
    memory_ops,
    omniparser_ops,
    open_data_ops,
    rag_ops,
    saas2_ops,
    saas_ops,
    screenpipe_ops,
    shell_ops,
    skyvern_ops,
    stagehand_ops,
    steel_ops,
    sys_plus_ops,
    web_search_ops,
    win_desk_ops,
    win_sys_ops,
)

Handler = Callable[[Dict[str, Any]], Dict[str, Any]]

_JINA_OPS = {"read_url", "jina", "url_md"}
_DOCLING_OPS = {"docling", "docling_convert"}


def _scrape(step: Dict[str, Any]) -> Dict[str, Any]:
    provider = str(step.get("provider") or step.get("engine") or "").strip().lower()
    op = str(step.get("_op") or "").strip().lower()
    if provider in {"jina"} or (not provider and op in _JINA_OPS):
        return jina_ops.read_url(step)
    return firecrawl_ops.scrape(step)


def _convert(step: Dict[str, Any]) -> Dict[str, Any]:
    engine = str(step.get("engine") or step.get("provider") or "").strip().lower()
    op = str(step.get("_op") or "").strip().lower()
    if engine in {"docling"} or (not engine and op in _DOCLING_OPS):
        return docling_ops.convert(step)
    return markitdown_ops.convert(step)


ROUTES: Dict[str, Handler] = {
    "scrape": _scrape,
    "firecrawl": _scrape,
    "firecrawl_scrape": _scrape,
    "read_url": _scrape,
    "jina": _scrape,
    "url_md": _scrape,
    "crawl": firecrawl_ops.crawl,
    "firecrawl_crawl": firecrawl_ops.crawl,
    "site_map": firecrawl_ops.site_map,
    "map": firecrawl_ops.site_map,
    "firecrawl_map": firecrawl_ops.site_map,
    "files_convert": _convert,
    "read_doc": _convert,
    "markitdown": _convert,
    "stagehand": stagehand_ops.act,
    "browser_act": stagehand_ops.act,
    "stagehand_act": stagehand_ops.act,
    "stagehand_extract": stagehand_ops.extract,
    "browser_extract": stagehand_ops.extract,
    "skyvern": skyvern_ops.run_task,
    "skyvern_task": skyvern_ops.run_task,
    "omni": omniparser_ops.parse,
    "omni_parse": omniparser_ops.parse,
    "omniparser": omniparser_ops.parse,
    "agentql": agentql_ops.query,
    "browser_query": agentql_ops.query,
    "page_query": agentql_ops.query,
    "files_find": everything_ops.find,
    "everything": everything_ops.find,
    "find_files": everything_ops.find,
    "memory_add": memory_ops.add,
    "mem0_add": memory_ops.add,
    "memory_search": memory_ops.search,
    "mem0_search": memory_ops.search,
    "composio": composio_ops.run,
    "composio_run": composio_ops.run,
    "mail_list": composio_ops.mail_list,
    "cal_next": composio_ops.cal_next,
    "drive_get": composio_ops.drive_get,
    "recall": screenpipe_ops.search,
    "screen_search": screenpipe_ops.search,
    "screenpipe": screenpipe_ops.search,
    "xlsx": graph_ops.xlsx,
    "excel": graph_ops.xlsx,
    "sheet": graph_ops.xlsx,
    "todo": graph_ops.todo,
    "todo_list": graph_ops.todo,
    "ms_todo": graph_ops.todo,
    "onenote": graph_ops.onenote,
    "onenote_list": graph_ops.onenote,
    "teams": graph_ops.teams,
    "teams_list": graph_ops.teams,
    "mail_send": graph_ops.mail_send,
    "send_mail": graph_ops.mail_send,
    "volume": win_desk_ops.volume,
    "vol": win_desk_ops.volume,
    "mute": win_desk_ops.volume,
    "winget": win_desk_ops.winget,
    "pkg_search": win_desk_ops.winget,
    "recycle": win_desk_ops.recycle,
    "recycle_bin": win_desk_ops.recycle,
    "trash": win_desk_ops.recycle,
    "eventlog": win_desk_ops.eventlog,
    "events": win_desk_ops.eventlog,
    "ocr_win": win_desk_ops.ocr_win,
    "win_ocr": win_desk_ops.ocr_win,
    "stt": win_desk_ops.stt,
    "speech_to_text": win_desk_ops.stt,
    "tts": win_desk_ops.tts,
    "speak": win_desk_ops.tts,
    "sapi": win_desk_ops.tts,
    "search": web_search_ops.search,
    "search_web": web_search_ops.search,
    "pplx_search": web_search_ops.search,
    "web_search": web_search_ops.search,
    "git": git_ops.git,
    "git_status": git_ops.git,
    "gh_pr": github_ops.gh_pr,
    "github_pr": github_ops.gh_pr,
    "pr_status": github_ops.gh_pr,
    "docling": _convert,
    "docling_convert": _convert,
    "rag": rag_ops.search,
    "rag_search": rag_ops.search,
    "winsearch": win_sys_ops.winsearch,
    "windows_search": win_sys_ops.winsearch,
    "steel_start": steel_ops.start_session,
    "steel": steel_ops.start_session,
    "steel_browser": steel_ops.start_session,
    "steel_stop": steel_ops.stop_session,
    "tavily": web_search_ops.search,
    "tavily_search": web_search_ops.search,
    "exa": web_search_ops.search,
    "exa_search": web_search_ops.search,
    "slack": saas_ops.slack,
    "slack_list": saas_ops.slack,
    "notion": saas_ops.notion,
    "notion_search": saas_ops.notion,
    "linear": saas_ops.linear,
    "linear_issues": saas_ops.linear,
    "pwsh": shell_ops.pwsh,
    "powershell": shell_ops.pwsh,
    "wsl": shell_ops.wsl,
    "docker": shell_ops.docker,
    "print": win_sys_ops.print_file,
    "print_file": win_sys_ops.print_file,
    "wifi": win_sys_ops.wifi,
    "wlan": win_sys_ops.wifi,
    "power": win_sys_ops.power,
    "battery": win_sys_ops.power,
    "disk": win_sys_ops.disk,
    "disk_free": win_sys_ops.disk,
    "whoami": win_sys_ops.whoami,
    "identity_local": win_sys_ops.whoami,
    "certs": win_sys_ops.certs,
    "cert_list": win_sys_ops.certs,
    "hash": win_sys_ops.file_hash,
    "sha256": win_sys_ops.file_hash,
    "file_hash": win_sys_ops.file_hash,
    "lnk": win_sys_ops.lnk,
    "shortcut": win_sys_ops.lnk,
    "dialog": win_sys_ops.dialog,
    "message_box": win_sys_ops.dialog,
    "cal_add": graph_ops.cal_add,
    "calendar_add": graph_ops.cal_add,
    "todo_add": graph_ops.todo_add,
    "task_add": graph_ops.todo_add,
    "contacts": graph_ops.contacts,
    "people": graph_ops.contacts,
    "drive_put": graph_ops.drive_put,
    "drive_upload": graph_ops.drive_put,
    "mail_reply": graph_ops.mail_reply,
    "ddg": web_search_ops.search,
    "duckduckgo": web_search_ops.search,
    "wiki": open_data_ops.wiki,
    "wikipedia": open_data_ops.wiki,
    "weather": open_data_ops.weather,
    "forecast": open_data_ops.weather,
    "rss": open_data_ops.rss,
    "feed": open_data_ops.rss,
    "hn": open_data_ops.hn,
    "hackernews": open_data_ops.hn,
    "arxiv": open_data_ops.arxiv,
    "jira": saas2_ops.jira,
    "jira_search": saas2_ops.jira,
    "discord": saas2_ops.discord,
    "airtable": saas2_ops.airtable,
    "trello": saas2_ops.trello,
    "asana": saas2_ops.asana,
    "gh_issue": github_ops.gh_issue,
    "github_issue": github_ops.gh_issue,
    "telegram": saas2_ops.telegram,
    "tg": saas2_ops.telegram,
    "serper": web_search_ops.search,
    "serper_search": web_search_ops.search,
    "brave": web_search_ops.search,
    "brave_search": web_search_ops.search,
    "zip": files_plus_ops.zip_files,
    "zip_files": files_plus_ops.zip_files,
    "unzip": files_plus_ops.unzip_files,
    "unzip_files": files_plus_ops.unzip_files,
    "files_mkdir": files_plus_ops.files_mkdir,
    "mkdir": files_plus_ops.files_mkdir,
    "files_stat": files_plus_ops.files_stat,
    "stat": files_plus_ops.files_stat,
    "tree": files_plus_ops.tree,
    "files_tree": files_plus_ops.tree,
    "diff_files": files_plus_ops.diff_files,
    "files_diff": files_plus_ops.diff_files,
    "sqlite": files_plus_ops.sqlite,
    "sql": files_plus_ops.sqlite,
    "pdf_info": files_plus_ops.pdf_info,
    "image_info": files_plus_ops.image_info,
    "b64": files_plus_ops.b64,
    "base64": files_plus_ops.b64,
    "which": sys_plus_ops.which,
    "where_exe": sys_plus_ops.which,
    "now": sys_plus_ops.now,
    "date_now": sys_plus_ops.now,
    "uuid_gen": sys_plus_ops.uuid_gen,
    "uuid": sys_plus_ops.uuid_gen,
    "ports": sys_plus_ops.ports,
    "netstat": sys_plus_ops.ports,
    "ip_addr": sys_plus_ops.ip_addr,
    "ipconfig": sys_plus_ops.ip_addr,
    "ping": sys_plus_ops.ping,
    "dns": sys_plus_ops.dns,
    "resolve": sys_plus_ops.dns,
    "uptime": sys_plus_ops.uptime,
    "brightness": sys_plus_ops.brightness,
    "lock_pc": sys_plus_ops.lock_pc,
    "lock_workstation": sys_plus_ops.lock_pc,
    "idle": sys_plus_ops.idle,
    "idle_time": sys_plus_ops.idle,
    "usb": sys_plus_ops.usb,
    "usb_list": sys_plus_ops.usb,
    "bluetooth": sys_plus_ops.bluetooth,
    "bt": sys_plus_ops.bluetooth,
    "printers": sys_plus_ops.printers,
    "printer_list": sys_plus_ops.printers,
    "bitlocker": sys_plus_ops.bitlocker,
    "bitlocker_status": sys_plus_ops.bitlocker,
    "defender": sys_plus_ops.defender,
    "defender_status": sys_plus_ops.defender,
    "win_updates": sys_plus_ops.win_updates,
    "windows_update": sys_plus_ops.win_updates,
    "fonts": sys_plus_ops.fonts,
    "font_list": sys_plus_ops.fonts,
    "dark_mode": sys_plus_ops.dark_mode,
    "theme": sys_plus_ops.dark_mode,
}


def dispatch(op: str, step: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    fn = ROUTES.get(op)
    if fn is None:
        return None
    payload = dict(step)
    payload.setdefault("_op", op)
    return fn(payload)


def capabilities() -> Dict[str, Any]:
    return {
        "firecrawl": True,
        "firecrawl_configured": firecrawl_ops.configured(),
        "markitdown": True,
        "stagehand": True,
        "stagehand_configured": stagehand_ops.configured(),
        "skyvern": True,
        "skyvern_configured": skyvern_ops.configured(),
        "omniparser": True,
        "omniparser_configured": omniparser_ops.configured(),
        "agentql": True,
        "agentql_configured": agentql_ops.configured(),
        "everything": True,
        "memory": True,
        "mem0_configured": memory_ops.mem0_configured(),
        "composio": True,
        "composio_configured": composio_ops.configured(),
        "screenpipe": True,
        "graph": True,
        "graph_configured": graph_ops.configured(),
        "jina": True,
        "git": True,
        "github": True,
        "github_configured": github_ops.configured(),
        "volume": True,
        "winget": True,
        "recycle": True,
        "eventlog": True,
        "ocr_win": True,
        "stt": True,
        "tts": True,
        "docling": True,
        "rag": True,
        "winsearch": True,
        "steel": True,
        "steel_configured": steel_ops.configured(),
        "tavily": True,
        "tavily_configured": web_search_ops.tavily_configured(),
        "exa": True,
        "exa_configured": web_search_ops.exa_configured(),
        "slack": True,
        "slack_configured": saas_ops.slack_configured(),
        "notion": True,
        "notion_configured": saas_ops.notion_configured(),
        "linear": True,
        "linear_configured": saas_ops.linear_configured(),
        "pwsh": True,
        "wsl": True,
        "docker": True,
        "print": True,
        "wifi": True,
        "power": True,
        "disk": True,
        "whoami": True,
        "certs": True,
        "hash": True,
        "lnk": True,
        "dialog": True,
        "open_data": True,
        "saas2": True,
        "files_plus": True,
        "sys_plus": True,
        "ddg": True,
        "wiki": True,
        "jira": True,
        "jira_configured": saas2_ops.jira_configured(),
        "discord": True,
        "discord_configured": saas2_ops.discord_configured(),
        "zip": True,
        "sqlite": True,
        "which": True,
        "lock_pc": True,
        "pilot": True,
        "live_seat": True,
        "session": True,
    }


def readiness() -> Dict[str, Any]:
    """Honest map: what works here vs Windows-only vs needs a key."""
    import sys

    from exo_control import search_ops
    from exo_control.win_native import WINDOWS_NATIVE_OPS

    ready = [
        "help", "observe", "whoami", "hash", "disk", "git", "rag",
        "files_stat", "zip", "which", "now", "uuid_gen", "ip_addr", "dns",
        "pilot", "goal", "proof", "changed", "undo", "heal",
        "session", "session_open", "session_status",
    ]
    windows_native = list(WINDOWS_NATIVE_OPS)
    on_windows = sys.platform == "win32"
    return {
        "ok": True,
        "honest": True,
        "on_windows": on_windows,
        "platform": sys.platform,
        "ready": ready,
        "windows_native": windows_native,
        "windows_only": [] if on_windows else list(windows_native),
        "needs_key": {
            "search": {"ok": search_ops.configured(), "env": "PERPLEXITY_API_KEY"},
            "tavily": {"ok": web_search_ops.tavily_configured(), "env": "TAVILY_API_KEY"},
            "exa": {"ok": web_search_ops.exa_configured(), "env": "EXA_API_KEY"},
            "firecrawl": {"ok": firecrawl_ops.configured(), "env": "FIRECRAWL_API_KEY"},
            "graph": {"ok": graph_ops.configured(), "env": "MICROSOFT_GRAPH_TOKEN"},
        },
        "stub": ["stt"],
    }
