"""Dispatch table for lease-free addon integrations."""
from __future__ import annotations

from typing import Any, Callable, Dict, Optional

from exo_control import (
    agentql_ops,
    composio_ops,
    everything_ops,
    firecrawl_ops,
    git_ops,
    github_ops,
    graph_ops,
    jina_ops,
    markitdown_ops,
    memory_ops,
    omniparser_ops,
    screenpipe_ops,
    skyvern_ops,
    stagehand_ops,
    win_desk_ops,
)

Handler = Callable[[Dict[str, Any]], Dict[str, Any]]

ROUTES: Dict[str, Handler] = {
    "scrape": firecrawl_ops.scrape,
    "firecrawl": firecrawl_ops.scrape,
    "firecrawl_scrape": firecrawl_ops.scrape,
    "crawl": firecrawl_ops.crawl,
    "firecrawl_crawl": firecrawl_ops.crawl,
    "site_map": firecrawl_ops.site_map,
    "map": firecrawl_ops.site_map,
    "firecrawl_map": firecrawl_ops.site_map,
    "files_convert": markitdown_ops.convert,
    "read_doc": markitdown_ops.convert,
    "markitdown": markitdown_ops.convert,
    "stagehand": stagehand_ops.act,
    "browser_act": stagehand_ops.act,
    "stagehand_act": stagehand_ops.act,
    "stagehand_extract": stagehand_ops.extract,
    "browser_extract": stagehand_ops.extract,
    "skyvern": skyvern_ops.run_task,
    "skyvern_task": skyvern_ops.run_task,
    "omni": omniparser_ops.parse,
    "omni_parse": omniparser_ops.parse,
    "omniparser": omniparser_ops.parse,
    "agentql": agentql_ops.query,
    "browser_query": agentql_ops.query,
    "page_query": agentql_ops.query,
    "files_find": everything_ops.find,
    "everything": everything_ops.find,
    "find_files": everything_ops.find,
    "memory_add": memory_ops.add,
    "mem0_add": memory_ops.add,
    "memory_search": memory_ops.search,
    "mem0_search": memory_ops.search,
    "composio": composio_ops.run,
    "composio_run": composio_ops.run,
    "mail_list": composio_ops.mail_list,
    "cal_next": composio_ops.cal_next,
    "drive_get": composio_ops.drive_get,
    "recall": screenpipe_ops.search,
    "screen_search": screenpipe_ops.search,
    "screenpipe": screenpipe_ops.search,
    "xlsx": graph_ops.xlsx,
    "excel": graph_ops.xlsx,
    "sheet": graph_ops.xlsx,
    "todo": graph_ops.todo,
    "todo_list": graph_ops.todo,
    "ms_todo": graph_ops.todo,
    "onenote": graph_ops.onenote,
    "onenote_list": graph_ops.onenote,
    "teams": graph_ops.teams,
    "teams_list": graph_ops.teams,
    "mail_send": graph_ops.mail_send,
    "send_mail": graph_ops.mail_send,
    "volume": win_desk_ops.volume,
    "vol": win_desk_ops.volume,
    "mute": win_desk_ops.volume,
    "winget": win_desk_ops.winget,
    "pkg_search": win_desk_ops.winget,
    "recycle": win_desk_ops.recycle,
    "recycle_bin": win_desk_ops.recycle,
    "trash": win_desk_ops.recycle,
    "eventlog": win_desk_ops.eventlog,
    "events": win_desk_ops.eventlog,
    "ocr_win": win_desk_ops.ocr_win,
    "win_ocr": win_desk_ops.ocr_win,
    "stt": win_desk_ops.stt,
    "speech_to_text": win_desk_ops.stt,
    "tts": win_desk_ops.tts,
    "speak": win_desk_ops.tts,
    "sapi": win_desk_ops.tts,
    "read_url": jina_ops.read_url,
    "jina": jina_ops.read_url,
    "url_md": jina_ops.read_url,
    "git": git_ops.git,
    "git_status": git_ops.git,
    "gh_pr": github_ops.gh_pr,
    "github_pr": github_ops.gh_pr,
    "pr_status": github_ops.gh_pr,
}


def dispatch(op: str, step: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    fn = ROUTES.get(op)
    if fn is None:
        return None
    return fn(step)


def capabilities() -> Dict[str, Any]:
    return {
        "firecrawl": True,
        "firecrawl_configured": firecrawl_ops.configured(),
        "markitdown": True,
        "stagehand": True,
        "stagehand_configured": stagehand_ops.configured(),
        "skyvern": True,
        "skyvern_configured": skyvern_ops.configured(),
        "omniparser": True,
        "omniparser_configured": omniparser_ops.configured(),
        "agentql": True,
        "agentql_configured": agentql_ops.configured(),
        "everything": True,
        "memory": True,
        "mem0_configured": memory_ops.mem0_configured(),
        "composio": True,
        "composio_configured": composio_ops.configured(),
        "screenpipe": True,
        "graph": True,
        "graph_configured": graph_ops.configured(),
        "jina": True,
        "git": True,
        "github": True,
        "github_configured": github_ops.configured(),
        "volume": True,
        "winget": True,
        "recycle": True,
        "eventlog": True,
        "ocr_win": True,
        "stt": True,
        "tts": True,
    }
