"""Harness-agnostic op catalog — any AI can self-describe the surface.

Used by exec ops ``help`` / ``ops`` / ``capabilities``, MCP instructions, and CLI.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional


# Compact catalog: op aliases → lease, purpose, common fields.
# Keep this the source of truth for agent discovery (not prose-only docs).
OPS: List[Dict[str, Any]] = [
    # Discovery / lease-free
    {"op": "help", "aliases": ["ops", "capabilities", "catalog"], "lease": False,
     "purpose": "List ops and harness rules for any AI", "fields": ["detail?", "query?"]},
    {"op": "status", "aliases": [], "lease": False, "purpose": "Driver health / capabilities", "fields": []},
    {"op": "stats", "aliases": [], "lease": False, "purpose": "Latency / reliability counters", "fields": ["reset?"]},
    {"op": "windows", "aliases": ["list_windows"], "lease": False,
     "purpose": "Top-level windows", "fields": ["monitor?"]},
    {"op": "monitors", "aliases": ["list_monitors"], "lease": False,
     "purpose": "Physical displays (id/left/top/width/height)", "fields": []},
    {"op": "observe", "aliases": ["compact_observe"], "lease": False,
     "purpose": "Compact a11y (+ optional OCR); token-capped", "fields": ["include_ocr?", "monitor?", "verbose?"]},
    {"op": "read", "aliases": ["read_ui"], "lease": False,
     "purpose": "Focused/target UIA tree (compact)", "fields": ["interactive?", "max_elements?"]},
    {"op": "eyes", "aliases": [], "lease": False,
     "purpose": "compact_observe + CDP endpoint summary", "fields": ["include_ocr?"]},
    {"op": "eyes_start", "aliases": [], "lease": False,
     "purpose": "Start live eyes loop (also auto on lease_acquire)", "fields": ["fps?", "ocr_on_change?"]},
    {"op": "eyes_stop", "aliases": [], "lease": False,
     "purpose": "Stop live eyes loop", "fields": []},
    {"op": "eyes_read", "aliases": ["look", "glance"], "lease": False,
     "purpose": "Glance at focused window (title + compact labels)", "fields": ["ocr?"]},
    {"op": "apps", "aliases": [], "lease": False, "purpose": "Running apps pid/title/exe", "fields": ["max?"]},
    {"op": "cdp", "aliases": ["cdp_discover", "exo_cdp"], "lease": False,
     "purpose": "Discover DevTools endpoints (Chrome/Edge/Exo WebView2)", "fields": ["port?"]},
    {"op": "wait_cdp", "aliases": ["wait_for_cdp"], "lease": False,
     "purpose": "Poll until CDP is up", "fields": ["timeout?", "port?", "poll?"]},
    {"op": "clipboard_get", "aliases": [], "lease": False, "purpose": "Read clipboard text", "fields": []},
    {"op": "notify", "aliases": [], "lease": True,
     "purpose": "Windows toast (real; stub only if step stub:true)", "fields": ["title", "body"]},
    {"op": "wait", "aliases": ["wait_until"], "lease": False,
     "purpose": "Wait for text/control; or all=/any= condition lists", "fields": ["text?", "query?", "all?", "any?", "timeout?", "poll?"]},
    {"op": "wait_all", "aliases": [], "lease": False,
     "purpose": "Wait until every condition succeeds", "fields": ["all|conditions", "timeout?"]},
    {"op": "wait_any", "aliases": [], "lease": False,
     "purpose": "Wait until any condition succeeds", "fields": ["any|conditions", "timeout?"]},
    {"op": "wait_gone", "aliases": [], "lease": False, "purpose": "Wait until control gone", "fields": ["query", "timeout?"]},
    {"op": "wait_change", "aliases": [], "lease": False,
     "purpose": "Wait for UI change or expect text", "fields": ["expect?", "timeout?"]},
    {"op": "wait_window", "aliases": [], "lease": False,
     "purpose": "Poll until window title/pid appears", "fields": ["title?", "pid?", "timeout?"]},
    {"op": "verify", "aliases": ["verify_ui"], "lease": False,
     "purpose": "Fail-closed UI assert", "fields": ["expect?", "expect_gone?", "timeout?"]},
    {"op": "last_error", "aliases": ["error", "last_fail"], "lease": False,
     "purpose": "Most recent failed step evidence (this engine)", "fields": []},
    {"op": "lease_acquire", "aliases": [], "lease": False,
     "purpose": "Hold desktop hands (required for mutating ops)", "fields": ["agent_id", "task?", "ttl_sec?"]},
    {"op": "lease_renew", "aliases": [], "lease": False, "purpose": "Extend lease", "fields": ["token?", "ttl_sec?"]},
    {"op": "lease_release", "aliases": [], "lease": False, "purpose": "Release desktop lease", "fields": ["token?"]},
    {"op": "lease_status", "aliases": [], "lease": False, "purpose": "Who holds the lease", "fields": []},
    {"op": "lease_force_release", "aliases": [], "lease": False,
     "purpose": "Clear lease by token, holder agent_id, or EXO_ALLOW_FORCE_RELEASE=1",
     "fields": ["token?", "agent_id?"]},
    {"op": "files_list", "aliases": [], "lease": False,
     "purpose": "List dir under allowroot", "fields": ["path", "max?", "confirm?"]},
    {"op": "files_read", "aliases": [], "lease": False, "purpose": "Read text file under allowroot", "fields": ["path"]},
    {"op": "registry_read", "aliases": [], "lease": False, "purpose": "Read registry values at path", "fields": ["path", "max?"]},
    {"op": "proc_list", "aliases": [], "lease": False, "purpose": "Process inventory", "fields": ["max?"]},
    {"op": "service_list", "aliases": [], "lease": False, "purpose": "Windows services", "fields": []},
    {"op": "service_status", "aliases": [], "lease": False, "purpose": "One service status", "fields": ["name"]},
    {"op": "search", "aliases": [
        "search_web", "pplx_search", "web_search",
        "tavily", "tavily_search", "exa", "exa_search",
        "ddg", "duckduckgo", "serper", "serper_search", "brave", "brave_search",
    ], "lease": False,
     "purpose": "Web search (lease-free; not UI find). provider=perplexity|tavily|exa|ddg|serper|brave",
     "fields": ["query", "provider?", "max?", "domains?", "contains?", "dedupe?", "rank?", "country?", "recency?"]},
    {"op": "search_content", "aliases": ["search_snippets", "pplx_content"], "lease": False,
     "purpose": "Query-relevant snippets scoped to urls via Perplexity Search",
     "fields": ["urls", "query?", "max?", "contains?"]},
    {"op": "scrape", "aliases": ["firecrawl", "firecrawl_scrape", "read_url", "jina", "url_md"], "lease": False,
     "purpose": "URL → markdown. provider=firecrawl|jina (FIRECRAWL_API_KEY or optional JINA_API_KEY)",
     "fields": ["url", "provider?", "verbose?"]},
    {"op": "crawl", "aliases": ["firecrawl_crawl"], "lease": False,
     "purpose": "Firecrawl site crawl (start or poll id=)",
     "fields": ["url?", "id?", "limit?"]},
    {"op": "site_map", "aliases": ["map", "firecrawl_map"], "lease": False,
     "purpose": "Firecrawl URL map (list links)",
     "fields": ["url", "max?"]},
    {"op": "files_convert", "aliases": ["read_doc", "markitdown", "docling", "docling_convert"], "lease": False,
     "purpose": "Allowrooted file → markdown. engine=markitdown|docling (txt/json/csv/html builtin)",
     "fields": ["path", "engine?", "verbose?", "confirm?"]},
    {"op": "stagehand", "aliases": ["browser_act", "stagehand_act"], "lease": False,
     "purpose": "Stagehand NL act on a page (BROWSERBASE_API_KEY / STAGEHAND_API_KEY)",
     "fields": ["instruction", "url?"]},
    {"op": "stagehand_extract", "aliases": ["browser_extract"], "lease": False,
     "purpose": "Stagehand NL extract → JSON",
     "fields": ["instruction", "url?", "schema?"]},
    {"op": "skyvern", "aliases": ["skyvern_task"], "lease": False,
     "purpose": "Skyvern vision browser task (SKYVERN_API_KEY)",
     "fields": ["task?", "url?", "run_id?"]},
    {"op": "omni", "aliases": ["omni_parse", "omniparser"], "lease": False,
     "purpose": "OmniParser screenshot → clickable elements (OMNIPARSER_URL)",
     "fields": ["path?", "image_b64?"]},
    {"op": "agentql", "aliases": ["browser_query", "page_query"], "lease": False,
     "purpose": "AgentQL query a URL → JSON (AGENTQL_API_KEY)",
     "fields": ["url", "query"]},
    {"op": "files_find", "aliases": ["everything", "find_files"], "lease": False,
     "purpose": "Find files (Everything HTTP, else walk allowroots)",
     "fields": ["query", "max?"]},
    {"op": "memory_add", "aliases": ["mem0_add"], "lease": False,
     "purpose": "Remember a fact (local JSONL; Mem0 if MEM0_API_KEY)",
     "fields": ["text", "user_id?"]},
    {"op": "memory_search", "aliases": ["mem0_search"], "lease": False,
     "purpose": "Recall stored facts",
     "fields": ["query", "user_id?", "max?"]},
    {"op": "composio", "aliases": ["composio_run"], "lease": False,
     "purpose": "Composio action (COMPOSIO_API_KEY; confirm for send/delete)",
     "fields": ["action", "input?", "confirm?"]},
    {"op": "mail_list", "aliases": [], "lease": False,
     "purpose": "Recent mail (Microsoft Graph token, else Composio)",
     "fields": ["max?"]},
    {"op": "cal_next", "aliases": [], "lease": False,
     "purpose": "Upcoming calendar events (Graph or Composio)",
     "fields": ["max?"]},
    {"op": "drive_get", "aliases": [], "lease": False,
     "purpose": "OneDrive/Graph item by path",
     "fields": ["path?"]},
    {"op": "recall", "aliases": ["screen_search", "screenpipe"], "lease": False,
     "purpose": "Search Screenpipe local screen/audio history",
     "fields": ["query?", "app?", "max?"]},
    {"op": "xlsx", "aliases": ["excel", "sheet"], "lease": False,
     "purpose": "Read CSV/TSV range under allowroots, or Graph workbook range",
     "fields": ["path?", "range?", "workbook?", "sheet?"]},
    {"op": "todo", "aliases": ["todo_list", "ms_todo"], "lease": False,
     "purpose": "Microsoft To Do lists/tasks (MICROSOFT_GRAPH_TOKEN)",
     "fields": ["list?", "max?"]},
    {"op": "onenote", "aliases": ["onenote_list"], "lease": False,
     "purpose": "OneNote notebooks/sections (Graph token)",
     "fields": ["notebook?", "max?"]},
    {"op": "teams", "aliases": ["teams_list"], "lease": False,
     "purpose": "Joined Teams or chats (Graph token)",
     "fields": ["kind?", "max?"]},
    {"op": "mail_send", "aliases": ["send_mail"], "lease": False,
     "purpose": "Send mail via Graph (confirm=true)",
     "fields": ["to", "subject?", "body?", "confirm"]},
    {"op": "volume", "aliases": ["vol", "mute"], "lease": False,
     "purpose": "Get/set system volume (set/mute needs confirm=true)",
     "fields": ["level?", "mute?", "confirm?"]},
    {"op": "winget", "aliases": ["pkg_search"], "lease": False,
     "purpose": "Search/list winget packages (Windows)",
     "fields": ["query?", "action?"]},
    {"op": "recycle", "aliases": ["recycle_bin", "trash"], "lease": False,
     "purpose": "Recycle bin list; empty needs confirm=true",
     "fields": ["action?", "confirm?"]},
    {"op": "eventlog", "aliases": ["events"], "lease": False,
     "purpose": "Compact Application/System event log (Windows)",
     "fields": ["log?", "max?"]},
    {"op": "ocr_win", "aliases": ["win_ocr"], "lease": False,
     "purpose": "WinRT OCR on an allowrooted image (Windows)",
     "fields": ["path?"]},
    {"op": "stt", "aliases": ["speech_to_text"], "lease": False,
     "purpose": "Windows Speech recognition (Windows)",
     "fields": []},
    {"op": "tts", "aliases": ["speak", "sapi"], "lease": False,
     "purpose": "SAPI speak (Windows)",
     "fields": ["text"]},
    {"op": "git", "aliases": ["git_status"], "lease": False,
     "purpose": "Allowrooted git status/diff/log",
     "fields": ["path", "action?"]},
    {"op": "gh_pr", "aliases": ["github_pr", "pr_status"], "lease": False,
     "purpose": "GitHub PR status (GITHUB_TOKEN)",
     "fields": ["repo", "number?"]},
    {"op": "rag", "aliases": ["rag_search"], "lease": False,
     "purpose": "Local keyword RAG over allowrooted text files",
     "fields": ["query", "max?"]},
    {"op": "winsearch", "aliases": ["windows_search"], "lease": False,
     "purpose": "Windows Search (Windows)",
     "fields": ["query"]},
    {"op": "steel_start", "aliases": ["steel", "steel_browser"], "lease": False,
     "purpose": "Start a Steel.dev cloud Chromium; returns cdp_url",
     "fields": ["timeout?"]},
    {"op": "steel_stop", "aliases": [], "lease": False,
     "purpose": "Stop a Steel.dev session",
     "fields": ["id"]},
    {"op": "slack", "aliases": ["slack_list"], "lease": False,
     "purpose": "Slack channels or post (post needs confirm=true)",
     "fields": ["action?", "channel?", "text?", "confirm?"]},
    {"op": "notion", "aliases": ["notion_search"], "lease": False,
     "purpose": "Notion search (NOTION_API_KEY)",
     "fields": ["query?", "max?"]},
    {"op": "linear", "aliases": ["linear_issues"], "lease": False,
     "purpose": "Linear issues (LINEAR_API_KEY)",
     "fields": ["query?", "max?"]},
    {"op": "pwsh", "aliases": ["powershell"], "lease": False,
     "purpose": "Run PowerShell (confirm=true)",
     "fields": ["script", "cwd?", "confirm"]},
    {"op": "wsl", "aliases": [], "lease": False,
     "purpose": "WSL list or exec (exec needs confirm=true)",
     "fields": ["action?", "command?", "distro?", "confirm?"]},
    {"op": "docker", "aliases": [], "lease": False,
     "purpose": "Docker ps/images or run/rm (mutate needs confirm=true)",
     "fields": ["action?", "image?", "id?", "confirm?"]},
    {"op": "print", "aliases": ["print_file"], "lease": False,
     "purpose": "Print an allowrooted file via the OS printer (not browser_pdf; confirm=true)",
     "fields": ["path", "confirm"]},
    {"op": "wifi", "aliases": ["wlan"], "lease": False,
     "purpose": "Wi-Fi status / networks (Windows)",
     "fields": []},
    {"op": "power", "aliases": ["battery"], "lease": False,
     "purpose": "Power status; sleep/hibernate need confirm=true",
     "fields": ["action?", "confirm?"]},
    {"op": "disk", "aliases": ["disk_free"], "lease": False,
     "purpose": "Disk usage for an allowroot (or default root)",
     "fields": ["path?"]},
    {"op": "whoami", "aliases": ["identity_local"], "lease": False,
     "purpose": "Current user and host",
     "fields": []},
    {"op": "certs", "aliases": ["cert_list"], "lease": False,
     "purpose": "Windows cert store or allowrooted cert file",
     "fields": ["path?"]},
    {"op": "hash", "aliases": ["sha256", "file_hash"], "lease": False,
     "purpose": "Hash an allowrooted file (sha256 default)",
     "fields": ["path", "algo?"]},
    {"op": "lnk", "aliases": ["shortcut"], "lease": False,
     "purpose": "Read/create a .lnk shortcut (create needs confirm=true)",
     "fields": ["path?", "target?", "confirm?"]},
    {"op": "dialog", "aliases": ["message_box"], "lease": False,
     "purpose": "Show a Windows message box (not a JS dialog; see browser_dialog; confirm=true)",
     "fields": ["text", "confirm"]},
    {"op": "cal_add", "aliases": ["calendar_add"], "lease": False,
     "purpose": "Create a calendar event (Graph; confirm=true)",
     "fields": ["subject", "start?", "end?", "confirm"]},
    {"op": "todo_add", "aliases": ["task_add"], "lease": False,
     "purpose": "Add a To Do task (Graph; confirm=true)",
     "fields": ["title", "list", "confirm"]},
    {"op": "contacts", "aliases": ["people"], "lease": False,
     "purpose": "List Outlook contacts (Graph token)",
     "fields": ["max?"]},
    {"op": "drive_put", "aliases": ["drive_upload"], "lease": False,
     "purpose": "Upload an allowrooted file to OneDrive (confirm=true)",
     "fields": ["path", "dest", "confirm"]},
    {"op": "mail_reply", "aliases": [], "lease": False,
     "purpose": "Reply to a Graph message (confirm=true)",
     "fields": ["id", "body", "confirm"]},
    {"op": "wiki", "aliases": ["wikipedia"], "lease": False,
     "purpose": "Wikipedia opensearch (no key)",
     "fields": ["query", "max?"]},
    {"op": "weather", "aliases": ["forecast"], "lease": False,
     "purpose": "Open-Meteo current weather (no key)",
     "fields": ["city?", "lat?", "lon?"]},
    {"op": "rss", "aliases": ["feed"], "lease": False,
     "purpose": "Read an RSS/Atom feed URL",
     "fields": ["url", "max?"]},
    {"op": "hn", "aliases": ["hackernews"], "lease": False,
     "purpose": "Hacker News search (Algolia, no key)",
     "fields": ["query?", "max?"]},
    {"op": "arxiv", "aliases": [], "lease": False,
     "purpose": "arXiv paper search (no key)",
     "fields": ["query", "max?"]},
    {"op": "jira", "aliases": ["jira_search"], "lease": False,
     "purpose": "Jira JQL search (JIRA_BASE + JIRA_API_TOKEN)",
     "fields": ["jql?", "max?"]},
    {"op": "discord", "aliases": [], "lease": False,
     "purpose": "Discord bot identity or post (post needs confirm=true)",
     "fields": ["channel?", "text?", "confirm?"]},
    {"op": "airtable", "aliases": [], "lease": False,
     "purpose": "Airtable records (AIRTABLE_API_KEY)",
     "fields": ["base", "table", "max?"]},
    {"op": "trello", "aliases": [], "lease": False,
     "purpose": "Trello boards (TRELLO_KEY + TRELLO_TOKEN)",
     "fields": []},
    {"op": "asana", "aliases": [], "lease": False,
     "purpose": "Asana tasks (ASANA_ACCESS_TOKEN)",
     "fields": ["workspace?", "max?"]},
    {"op": "gh_issue", "aliases": ["github_issue"], "lease": False,
     "purpose": "List or create GitHub issues (create needs confirm=true)",
     "fields": ["repo", "title?", "confirm?"]},
    {"op": "telegram", "aliases": ["tg"], "lease": False,
     "purpose": "Telegram sendMessage (confirm=true)",
     "fields": ["chat_id", "text", "confirm"]},
    {"op": "zip", "aliases": ["zip_files"], "lease": False,
     "purpose": "Zip an allowrooted file/dir",
     "fields": ["path", "dest"]},
    {"op": "unzip", "aliases": ["unzip_files"], "lease": False,
     "purpose": "Unzip into an allowroot (confirm=true)",
     "fields": ["path", "dest?", "confirm"]},
    {"op": "files_mkdir", "aliases": ["mkdir"], "lease": False,
     "purpose": "Create an allowrooted directory",
     "fields": ["path"]},
    {"op": "files_stat", "aliases": ["stat", "pdf_info", "image_info"], "lease": False,
     "purpose": "Stat an allowrooted path (PDF/image extras when the suffix matches)",
     "fields": ["path"]},
    {"op": "tree", "aliases": ["files_tree"], "lease": False,
     "purpose": "List allowrooted tree entries",
     "fields": ["path?", "max?"]},
    {"op": "diff_files", "aliases": ["files_diff"], "lease": False,
     "purpose": "Unified diff of two allowrooted text files",
     "fields": ["a", "b"]},
    {"op": "sqlite", "aliases": ["sql"], "lease": False,
     "purpose": "Query an allowrooted SQLite DB (writes need confirm=true)",
     "fields": ["path", "sql", "confirm?"]},
    {"op": "b64", "aliases": ["base64"], "lease": False,
     "purpose": "Base64-encode an allowrooted file",
     "fields": ["path", "action?"]},
    {"op": "which", "aliases": ["where_exe"], "lease": False,
     "purpose": "Resolve an executable on PATH",
     "fields": ["name"]},
    {"op": "now", "aliases": ["date_now"], "lease": False,
     "purpose": "Current UTC time",
     "fields": []},
    {"op": "uuid_gen", "aliases": ["uuid"], "lease": False,
     "purpose": "Generate a UUID4",
     "fields": []},
    {"op": "ports", "aliases": ["netstat"], "lease": False,
     "purpose": "Listening ports (Windows)",
     "fields": []},
    {"op": "ip_addr", "aliases": ["ipconfig"], "lease": False,
     "purpose": "Local host addresses",
     "fields": []},
    {"op": "ping", "aliases": [], "lease": False,
     "purpose": "One ICMP ping",
     "fields": ["host"]},
    {"op": "dns", "aliases": ["resolve"], "lease": False,
     "purpose": "DNS lookup",
     "fields": ["host"]},
    {"op": "uptime", "aliases": [], "lease": False,
     "purpose": "System uptime",
     "fields": []},
    {"op": "brightness", "aliases": [], "lease": False,
     "purpose": "Display brightness (Windows)",
     "fields": []},
    {"op": "lock_pc", "aliases": ["lock_workstation"], "lease": False,
     "purpose": "Lock the workstation (confirm=true)",
     "fields": ["confirm"]},
    {"op": "idle", "aliases": ["idle_time"], "lease": False,
     "purpose": "Input idle time (Windows)",
     "fields": []},
    {"op": "usb", "aliases": ["usb_list"], "lease": False,
     "purpose": "USB devices (Windows)",
     "fields": []},
    {"op": "bluetooth", "aliases": ["bt"], "lease": False,
     "purpose": "Bluetooth devices (Windows)",
     "fields": []},
    {"op": "printers", "aliases": ["printer_list"], "lease": False,
     "purpose": "Installed printers (Windows)",
     "fields": []},
    {"op": "bitlocker", "aliases": ["bitlocker_status"], "lease": False,
     "purpose": "BitLocker status only (Windows; no unlock)",
     "fields": []},
    {"op": "defender", "aliases": ["defender_status"], "lease": False,
     "purpose": "Microsoft Defender status only (Windows; no disable)",
     "fields": []},
    {"op": "win_updates", "aliases": ["windows_update"], "lease": False,
     "purpose": "List Windows Update state (Windows)",
     "fields": []},
    {"op": "fonts", "aliases": ["font_list"], "lease": False,
     "purpose": "Installed fonts (Windows)",
     "fields": []},
    {"op": "dark_mode", "aliases": ["theme"], "lease": False,
     "purpose": "Dark mode status (Windows)",
     "fields": []},
    {"op": "env_get", "aliases": [], "lease": False, "purpose": "Env var", "fields": ["name"]},
    {"op": "env_list", "aliases": [], "lease": False, "purpose": "Env var names (values via env_get)", "fields": ["max?"]},
    {"op": "tasks_list", "aliases": [], "lease": False, "purpose": "Scheduled tasks (compact)", "fields": ["max?"]},
    {"op": "startup_list", "aliases": [], "lease": False, "purpose": "Startup folder entries", "fields": ["max?"]},
    {"op": "observe_budget", "aliases": [], "lease": False,
     "purpose": "Warm compact_observe p50/p95 ms + chars", "fields": ["n?"]},
    {"op": "kill_switch", "aliases": ["arm_kill_switch", "disarm_kill_switch"], "lease": False,
     "purpose": "Arm/disarm global kill (blocks hands)", "fields": ["armed?"]},
    {"op": "action_log", "aliases": ["log", "recent_actions"], "lease": False,
     "purpose": "Recent mutating injects", "fields": ["n?"]},
    {"op": "goal", "aliases": ["intent"], "lease": False,
     "purpose": "Declare the job (Pilot). Later proof/heal/skills attach to this intent",
     "fields": ["text"]},
    {"op": "checkpoint", "aliases": [], "lease": False,
     "purpose": "Mark Pilot progress toward the current goal",
     "fields": ["note", "done?"]},
    {"op": "proof", "aliases": [], "lease": False,
     "purpose": "Evidence pack: goal, checkpoints, last glance, last error",
     "fields": []},
    {"op": "changed", "aliases": ["what_changed"], "lease": False,
     "purpose": "Structured diff of the last two observe/read glances (added/removed labels)",
     "fields": []},
    {"op": "undo", "aliases": [], "lease": False,
     "purpose": "Reverse the last reversible mutation (files_write/delete, clipboard_set)",
     "fields": []},
    {"op": "skill_save", "aliases": [], "lease": False,
     "purpose": "Save this script's successful hands as a named skill",
     "fields": ["name", "steps?"]},
    {"op": "skill_run", "aliases": ["replay"], "lease": False,
     "purpose": "Replay a saved skill (inner steps still honor lease/confirm)",
     "fields": ["name"]},
    {"op": "skill_list", "aliases": [], "lease": False,
     "purpose": "List saved Pilot skills",
     "fields": []},
    {"op": "heal", "aliases": [], "lease": False,
     "purpose": "One bounded retry of the last failed hand (after you fix lease/focus)",
     "fields": []},
    # Hands (lease required)
    {"op": "focus", "aliases": ["smart_focus"], "lease": True,
     "purpose": "Foreground window by title/pid; optional monitor bind", "fields": ["title?", "pid?", "monitor?"]},
    {"op": "click", "aliases": ["smart_click"], "lease": True,
     "purpose": "UIA-first click by query, ref (eN from read/observe), or x,y",
     "fields": ["query?", "ref?", "x?", "y?", "require_change?", "screenshot_on_fail?"]},
    {"op": "type", "aliases": ["smart_type"], "lease": True,
     "purpose": "Type text (optional focus query/ref); paste fallback if needed",
     "fields": ["text", "query?", "ref?", "clear?", "confirm?"]},
    {"op": "fill", "aliases": [], "lease": True,
     "purpose": "Fill fields {label: value} or query+text sugar",
     "fields": ["fields?", "query?", "text?", "submit?", "confirm?"]},
    {"op": "scroll", "aliases": ["smart_scroll"], "lease": True,
     "purpose": "Aimed SendInput wheel (never Home/End). Positive = page down.",
     "fields": ["notches?", "direction?", "amount?", "dy?", "dx?", "query?"]},
    {"op": "scroll_into_view", "aliases": ["into_view"], "lease": True,
     "purpose": "Wheel until query/bbox is in the document viewport",
     "fields": ["query?", "bbox?", "max_steps?"]},
    {"op": "hover", "aliases": [], "lease": True,
     "purpose": "Move pointer like a person (hover menus/tooltips)",
     "fields": ["query?", "x?", "y?"]},
    {"op": "drag", "aliases": ["smart_drag"], "lease": True, "purpose": "Drag", "fields": ["x1", "y1", "x2", "y2"]},
    {"op": "hotkey", "aliases": ["smart_hotkey", "keys", "press"], "lease": True,
     "purpose": "Hotkey chord", "fields": ["keys"]},
    {"op": "screenshot", "aliases": ["shot"], "lease": True,
     "purpose": "JPEG/path capture; monitor/title bind fail-closed", "fields": ["title?", "monitor?", "path?", "max_side?"]},
    {"op": "launch", "aliases": ["start", "run"], "lease": True,
     "purpose": "Fuzzy app launch + wait_ready default for app names",
     "fields": ["app?", "name?", "command?", "wait_ready?", "title?", "timeout?", "args?", "focus?", "confirm?"]},
    {"op": "open", "aliases": ["open_path", "open_url"], "lease": True,
     "purpose": "Shell-open path/url", "fields": ["path?", "url?", "target?"]},
    {"op": "window_min", "aliases": ["window_minimize"], "lease": True, "purpose": "Minimize", "fields": ["title?", "hwnd?"]},
    {"op": "window_max", "aliases": ["window_maximize"], "lease": True, "purpose": "Maximize", "fields": ["title?", "hwnd?"]},
    {"op": "window_restore", "aliases": [], "lease": True, "purpose": "Restore", "fields": ["title?", "hwnd?"]},
    {"op": "window_close", "aliases": [], "lease": True,
     "purpose": "Close window (default: Don't save on unsaved prompts)", "fields": ["title?", "hwnd?", "discard_unsaved?"]},
    {"op": "window_move", "aliases": ["window_resize", "window_snap"], "lease": True,
     "purpose": "Move/resize/snap the focused window (SetWindowPos)",
     "fields": ["title?", "hwnd?", "x?", "y?", "w?", "h?", "snap?"]},
    {"op": "clipboard_set", "aliases": [], "lease": True, "purpose": "Set clipboard text", "fields": ["text"]},
    {"op": "clipboard_image_set", "aliases": ["clipboard_set_image"], "lease": True,
     "purpose": "Put image file on clipboard", "fields": ["path"]},
    {"op": "clipboard_image_save", "aliases": [], "lease": False,
     "purpose": "Save clipboard image to path", "fields": ["path"]},
    {"op": "files_write", "aliases": [], "lease": True,
     "purpose": "Write text under allowroot", "fields": ["path", "text", "confirm?"]},
    {"op": "files_copy", "aliases": [], "lease": True, "purpose": "Copy file", "fields": ["path", "dest", "confirm?"]},
    {"op": "files_move", "aliases": [], "lease": True, "purpose": "Move file", "fields": ["path", "dest", "confirm?"]},
    {"op": "files_delete", "aliases": [], "lease": True,
     "purpose": "Delete file (confirm for recursive/outside roots)", "fields": ["path", "confirm?"]},
    {"op": "registry_write", "aliases": [], "lease": True,
     "purpose": "Write HKCU (confirm); HKLM write denied", "fields": ["path", "name", "value", "confirm"]},
    {"op": "proc_kill", "aliases": [], "lease": True,
     "purpose": "Kill process (confirm; anti-cheat hard-deny by name or pid)", "fields": ["pid?", "name?", "confirm"]},
    {"op": "service_control", "aliases": [], "lease": True,
     "purpose": "start/stop/restart service", "fields": ["name", "action", "confirm"]},
    {"op": "desktop", "aliases": [], "lease": "switch", "purpose": "Virtual desktop list/switch", "fields": ["action?"]},
    # Browser
    {"op": "browser_connect", "aliases": [], "lease": True,
     "purpose": "Connect CDP browser (local loopback, or provider=browser-use cloud)",
     "fields": ["cdp_url?", "endpoint?", "port?", "provider?"]},
    {"op": "browser_use", "aliases": ["browser_use_task", "browser_use_run"], "lease": False,
     "purpose": "Browser Use hosted agent run (task=… or poll run_id=…)",
     "fields": ["task?", "run_id?", "wait?", "session_id?"]},
    {"op": "browser_use_start", "aliases": ["browser_cloud"], "lease": False,
     "purpose": "Start a Browser Use cloud Chromium; returns cdp_url",
     "fields": ["country?", "profile_id?", "session_timeout?"]},
    {"op": "browser_use_stop", "aliases": [], "lease": False,
     "purpose": "Stop a Browser Use cloud browser session", "fields": ["id?"]},
    {"op": "ego", "aliases": ["ego_status", "ego_lite"], "lease": False,
     "purpose": "ego lite status (macOS app; Exo is Windows-only — use browser_* or browser_use)",
     "fields": []},
    {"op": "browser_spaces", "aliases": [], "lease": True, "purpose": "List browser spaces", "fields": []},
    {"op": "browser_create_space", "aliases": [], "lease": True, "purpose": "New space", "fields": []},
    {"op": "browser_navigate", "aliases": [], "lease": True, "purpose": "Navigate", "fields": ["url", "space_id?"]},
    {"op": "browser_snapshot", "aliases": [], "lease": True,
     "purpose": "DOM snapshot with refs (compact)", "fields": ["space_id?", "include_screenshot?", "verbose?"]},
    {"op": "browser_click", "aliases": [], "lease": True,
     "purpose": "Click by ref/text/selector", "fields": ["ref?", "text?", "name?", "query?", "selector?", "space_id?"]},
    {"op": "browser_type", "aliases": [], "lease": True, "purpose": "Type in browser", "fields": ["text", "ref?", "space_id?"]},
    {"op": "browser_press", "aliases": [], "lease": True, "purpose": "Key in browser", "fields": ["key", "space_id?"]},
    {"op": "browser_scroll", "aliases": [], "lease": True,
     "purpose": "Scroll the page document (DOM scrollBy, not chrome)",
     "fields": ["dy?", "dx?", "notches?", "direction?", "query?", "selector?", "ref?", "space_id?"]},
    {"op": "browser_scroll_into_view", "aliases": ["browser_into_view"], "lease": True,
     "purpose": "DOM scrollIntoView for text/selector/ref",
     "fields": ["text?", "selector?", "ref?", "space_id?"]},
    {"op": "browser_hover", "aliases": [], "lease": True,
     "purpose": "Hover a page element", "fields": ["text?", "selector?", "ref?", "space_id?"]},
    {"op": "browser_wait", "aliases": [], "lease": True,
     "purpose": "Wait for text/name", "fields": ["text?", "name?", "timeout?", "space_id?"]},
    {"op": "browser_fill", "aliases": [], "lease": True, "purpose": "Fill form fields", "fields": ["fields", "space_id?"]},
    {"op": "browser_eval", "aliases": [], "lease": True,
     "purpose": "Evaluate JS (confirm required; EXO_DENY_BROWSER_EVAL=1 hard-denies)",
     "fields": ["js", "space_id?", "confirm"]},
    {"op": "browser_close_space", "aliases": [], "lease": True, "purpose": "Close space", "fields": ["space_id"]},
    {"op": "browser_network", "aliases": ["browser_har"], "lease": True,
     "purpose": "Recent page request log (HAR-lite)",
     "fields": ["space_id?", "max?"]},
    {"op": "browser_downloads", "aliases": [], "lease": True,
     "purpose": "Recent browser downloads",
     "fields": ["space_id?", "max?"]},
    {"op": "browser_pdf", "aliases": ["browser_print"], "lease": True,
     "purpose": "Print the page to an allowrooted PDF (not OS print)",
     "fields": ["path", "space_id?"]},
    {"op": "browser_tabs", "aliases": ["browser_switch"], "lease": True,
     "purpose": "List or switch browser spaces/tabs",
     "fields": ["space_id?", "index?", "url?"]},
    {"op": "browser_back", "aliases": [], "lease": True, "purpose": "History back", "fields": ["space_id?"]},
    {"op": "browser_forward", "aliases": [], "lease": True, "purpose": "History forward", "fields": ["space_id?"]},
    {"op": "browser_reload", "aliases": [], "lease": True, "purpose": "Reload page", "fields": ["space_id?"]},
    {"op": "browser_select", "aliases": [], "lease": True,
     "purpose": "Select an option in a <select>",
     "fields": ["selector", "value", "space_id?"]},
    {"op": "browser_upload", "aliases": [], "lease": True,
     "purpose": "Set an allowrooted file on a file input",
     "fields": ["selector", "path", "space_id?"]},
    {"op": "browser_dialog", "aliases": [], "lease": True,
     "purpose": "Arm accept/dismiss for the next JS dialog (not OS MessageBox)",
     "fields": ["action?", "text?", "space_id?"]},
    {"op": "browser_storage", "aliases": [], "lease": True,
     "purpose": "Read page localStorage/sessionStorage",
     "fields": ["kind?", "space_id?"]},
    {"op": "browser_cookies", "aliases": [], "lease": True,
     "purpose": "Cookie names/domains (values need confirm=true)",
     "fields": ["space_id?", "confirm?"]},
    {"op": "browser_console", "aliases": [], "lease": True,
     "purpose": "Recent page console messages",
     "fields": ["space_id?", "max?"]},
    {"op": "browser_viewport", "aliases": [], "lease": True,
     "purpose": "Get/set page viewport",
     "fields": ["width?", "height?", "space_id?"]},
    {"op": "cursor_exec", "aliases": ["cursor_run"], "lease": True,
     "purpose": "Run steps on a named virtual cursor", "fields": ["cursor_id?", "steps"]},
    {"op": "create_cursor", "aliases": ["cursor_create"], "lease": True,
     "purpose": "Create a named virtual cursor", "fields": ["cursor_id?"]},
    {"op": "list_cursors", "aliases": ["cursors"], "lease": False,
     "purpose": "List virtual cursors", "fields": []},
]

HARNESS_RULES: List[str] = [
    "Works with ANY AI via MCP (stdio), CLI, or Python — not tied to one vendor.",
    "Script-first: prefer one batched exec with many steps over chatty single clicks.",
    "Acquire lease_acquire before hands (click/type/launch/browser/files write).",
    "You are a person in the chair: aim the pointer, wheel the document, glance after hands.",
    "Scroll with scroll / scroll_into_view / browser_scroll. Never Home/End (they jump the caret).",
    "Eyes first: observe/read/windows/verify; screenshots only when structure is insufficient.",
    "Hands attach a compact seen glance when live eyes are running (seen:false to skip).",
    "Compact by default; set verbose=true only when you need full trees.",
    "Focus by title; WinUI host ranks above WebView2 child windows.",
    "monitor=N binds focus/observe/shot to that display; wrong-monitor fails closed.",
    "confirm=true is an agent assertion, not a human prompt. Destructive OS ops still need it.",
    "Files outside EXO_FILE_ROOTS stay denied unless the operator sets EXO_ALLOW_OUTSIDE_ROOTS=1.",
    "lease_status never returns the token. force_release needs token, holder, or EXO_ALLOW_FORCE_RELEASE=1.",
    "Always lease_release when done (or let TTL expire).",
    "Never invent UI state — use step results / observe / verify / seen.",
    "search is lease-free web retrieval (provider=perplexity|tavily|exa|ddg|serper|brave). Use browser_* to operate a page.",
    "browser_use is Browser Use Cloud (BROWSER_USE_API_KEY): hosted task or cloud Chromium CDP.",
    "scrape = URL→markdown (provider=firecrawl|jina). files_convert = file→markdown (engine=markitdown|docling).",
    "stagehand / browser_act and agentql / browser_query are lease-free HTTP (not local CDP hands).",
    "skyvern = vision forms. omni = screenshot parse. recall = Screenpipe. memory_* = local/Mem0.",
    "mail_list / cal_next / drive_get / todo / onenote / teams = Graph. mail_send needs confirm=true.",
    "git = allowrooted status/diff. gh_pr = GitHub API. xlsx = local CSV or Graph.",
    "volume/winget/recycle/eventlog/ocr_win/stt/tts are Windows desk ops (set/empty need confirm).",
    "rag = local docs. steel_start = cloud Chromium. slack/notion/linear posts need confirm.",
    "pwsh/wsl exec/docker run, print, dialog, power sleep, lnk create need confirm=true.",
    "Waves 3–5: Graph writes, CDP extras, ddg/wiki/weather/hn, more SaaS, zip/sqlite/tree, which/dns/lock_pc.",
    "Pilot (original): goal → hands → checkpoint → proof. changed diffs glances. undo reverses writes. skill_save/run is muscle memory. heal retries the last miss once.",
    "Exo Control is Windows-only. ego lite has no Windows app — use browser_* spaces, not ego-browser.",
]

MINIMAL_SCRIPT_EXAMPLE: List[Dict[str, Any]] = [
    {"op": "lease_acquire", "agent_id": "any-agent", "task": "demo", "ttl_sec": 120},
    {"op": "launch", "app": "notepad"},
    {"op": "focus", "title": "Notepad"},
    {"op": "type", "text": "hello from exo-control"},
    {"op": "notify", "title": "Exo Control", "body": "Done"},
    {"op": "lease_release"},
]


CORE_OPS = (
    "help", "status", "lease_acquire", "lease_release", "lease_status",
    "launch", "focus", "read", "observe", "click", "type", "scroll",
    "scroll_into_view", "hover", "verify", "wait", "screenshot",
)


def _names(entry: Dict[str, Any]) -> List[str]:
    return [entry["op"], *list(entry.get("aliases") or [])]


def lease_required_ops() -> frozenset:
    names = set()
    for entry in OPS:
        if entry.get("lease") in {True, "switch"}:
            names.update(_names(entry))
    return frozenset(names)


def lease_free_ops() -> frozenset:
    names = set()
    for entry in OPS:
        if entry.get("lease") is False:
            names.update(_names(entry))
    return frozenset(names)


def known_ops() -> frozenset:
    names = set()
    for entry in OPS:
        names.update(_names(entry))
    return frozenset(names)


def get_op(name: str) -> Optional[Dict[str, Any]]:
    key = (name or "").strip().lower()
    if not key:
        return None
    for entry in OPS:
        if key in {n.lower() for n in _names(entry)}:
            return entry
    return None


def list_ops(*, query: Optional[str] = None, detail: bool = False, compact: Optional[bool] = None) -> Dict[str, Any]:
    q = (query or "").strip().lower()
    want_compact = compact if compact is not None else (not detail and not q)
    rows = []
    for entry in OPS:
        names = _names(entry)
        if q and not any(q in n for n in names) and q not in (entry.get("purpose") or "").lower():
            continue
        if want_compact and entry["op"] not in CORE_OPS:
            continue
        row = {
            "op": entry["op"],
            "aliases": list(entry.get("aliases") or []),
            "lease": entry.get("lease"),
            "purpose": entry.get("purpose"),
        }
        if detail:
            row["fields"] = list(entry.get("fields") or [])
        rows.append(row)
    from exo_control.policy import identity

    ident = identity()
    return {
        "ok": True,
        "count": len(rows),
        "ops": rows,
        "compact": want_compact,
        "total_ops": len(OPS),
        "hint": "pass detail=true or query=… for the full catalog" if want_compact else None,
        "rules": list(HARNESS_RULES) if detail or q else HARNESS_RULES[:5],
        "example": list(MINIMAL_SCRIPT_EXAMPLE),
        "identity": ident,
        "surfaces": {
            "mcp": "python -m exo_control.slim_mcp_server",
            "cli": "exo-control exec",
            "python": "from exo_control import ExoExecEngine",
        },
        "tools": {
            "mcp": ["exo_exec", "exo_screenshot", "exo_help"],
            "note": "aether_* aliases only when EXO_MCP_ALIASES=1.",
        },
    }


def mcp_instructions() -> str:
    return (
        "Exo Control — realtime Windows eyes/hands for ANY AI harness (MCP/CLI/Python). "
        "Use exo_exec with a JSON array of steps. "
        "Always start mutating work with {\"op\":\"lease_acquire\",\"agent_id\":\"…\",\"task\":\"…\"} "
        "and end with lease_release. Prefer structure: focus → observe/read → click/type/scroll → verify. "
        "Scroll with aimed wheel (scroll / scroll_into_view / browser_scroll). Never Home/End. "
        "Hands attach a compact seen glance. Screenshots only when pixels matter (exo_screenshot). "
        "Call exo_help or step {\"op\":\"help\"} for ops (detail=true for the full catalog). "
        "Web facts: {\"op\":\"search\",\"query\":[\"…\"],\"provider\":\"perplexity\"}. "
        "Page to markdown: {\"op\":\"scrape\",\"url\":\"…\",\"provider\":\"firecrawl|jina\"}. "
        "Cloud browser agent: {\"op\":\"browser_use\",\"task\":\"…\"} (BROWSER_USE_API_KEY). "
        "Page UI: browser_*. Docs: files_convert (engine=markitdown|docling) / files_find / xlsx. "
        "Pilot: goal / checkpoint / proof / changed / undo / skill_save / skill_run / heal. "
        "Graph: mail_list / todo / onenote / teams / mail_send. git / gh_pr. "
        "Exo is Windows-only; ego lite has no Windows app. "
        "Example: [{\"op\":\"lease_acquire\",\"agent_id\":\"agent\",\"task\":\"demo\",\"ttl_sec\":120},"
        "{\"op\":\"launch\",\"app\":\"notepad\"},{\"op\":\"type\",\"text\":\"hi\"},{\"op\":\"lease_release\"}]. "
        "Hard rules: confirm=true for destructive OS ops; never kill anti-cheat; compact by default; "
        "do not invent UI state."
    )
